project:
  type: website
  output-dir: docs

website:
  title: "Lesson Plans for Linguistic Data Analysis with R"
  favicon: EKB_2023_icon.png
  page-footer: 
    right: "Copyright: Earl Kjar Brown, PhD"
    border: false
    background: light
  sidebar: 
    contents:
      - text: "Home"
        file: index.qmd
      - section: "Basics"
        contents:
          - lessons/r_rstudio.qmd
          - lessons/programming_basics.qmd
          - lessons/data_structures.qmd
    style: "docked"
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

