project:
  type: website
  output-dir: docs

website:
  title: "Lesson Plans for Linguistic Data Analysis with R"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  page-footer: 
    right: "Copyright: Earl Kjar Brown, PhD"
    border: false
    background: light
  sidebar: 
    # contents: auto
    contents:
      - text: "Home"
        file: index.qmd
      - r_rstudio.qmd
    style: "docked"
    search: true
    # contents:
    #   - section: "Basics"
    #     contents: 
    #       - index.qmd
    #   - section: "Data Wrangling"
    #     contents:
    #       - about.qmd
    # type: dark
    # border: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

