project:
  type: website
  output-dir: docs

website:
  title: "Lesson Plans for Linguistic Data Analysis with R"
  favicon: EKB_2023_icon.png
  page-footer: 
    right: "Copyright: Earl Kjar Brown, PhD"
    border: false
    background: light
  sidebar: 
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - section: "Basics"
        contents:
          - lessons/r_rstudio.qmd
          - lessons/programming_basics.qmd
          - lessons/data_structures.qmd
          - lessons/File_IO.qmd
          - lessons/regexes.qmd
      - section: "Frequency"
        contents:
          - lessons/create_freq.qmd
          - lessons/webscrape_freq.qmd
          - lessons/quanteda.qmd
      - section: "Wrangling"
        contents:
          - lessons/wrangling.qmd
      - section: "Visualization"
        contents:
          - lessons/visualization.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

